name: HotbarMenuItem
version: 1.0
main: me.angel.hotbarmenuitem.HotbarMenuItem
api-version: 1.20
author: Angel
description: Plugin para dar un ítem fijo y personalizado en la hotbar.
commands: {}
permissions: {}
